chore: setup build and test scripts
antvis/graphlib pull request #5
Opened 2022-12-15 03:10 UTC by YiSiWang

添加构建和测试脚本

- 构建和 G2 保持一致，产生 umd cjs esm 三种输出， umd 使用 rollup ，其他使用 tsc
- 单测和 G2 保持一致，放在 `__test__/*.spec.ts`

2022-12-16 03:34 UTC, hustcc requested changes

2022-12-16 03:34 UTC, hustcc commented on jest.config.js
> +  // testEnvironment: 'jest-electron/environment',
注释的都删除，应该不需要了。

2022-12-16 03:34 UTC, hustcc commented on jest.config.js
> +  preset: 'ts-jest/presets/js-with-ts',
ts-jest

2022-12-16 03:34 UTC, hustcc commented on jest.config.js
> +  //   '<rootDir>/__tests__/unit/(statistic|infer|composition|interaction|runtime|interaction|mark|shape)',
删除。

2022-12-16 03:34 UTC, hustcc commented on package.json
> +    "build:umd": "rimraf ./dist && rollup -c && npm run size",
可以不需要 umd？可以少很多 devdependence。

2022-12-16 03:35 UTC, hustcc commented
目标分支名，可以直接交 `2.0`，不用加 `-dev`

2022-12-16 03:41 UTC, YiSiWang commented on package.json
> +    "build:umd": "rimraf ./dist && rollup -c && npm run size",
雀食，如果是比较底层的包，没有必要 umd

2022-12-19 08:29 UTC, YiSiWang commented
@hustcc 都改好了

2022-12-20 03:23 UTC, hustcc requested changes

2022-12-20 03:23 UTC, hustcc commented on .github/workflows/build.yml
> +      - 2.0-dev
这里分支名没有修改~

2022-12-20 03:42 UTC, hustcc approved these changes

2022-12-20 03:42 UTC, merged