feat: add API interfaces
antvis/graphlib pull request #6
Opened 2022-12-16 03:23 UTC by YiSiWang

添加 API 接口类型定义，大部分带注释，没有注释的在实现的时候补充

2022-12-16 11:21 UTC, pomelo-nwu commented on src/Graph.ts
> +export class Graph<
四哥代码写的真好，赏心悦目！

2022-12-20 11:52 UTC, hustcc requested changes

2022-12-20 11:52 UTC, hustcc commented on src/index.ts
> +export * from './types';
export type * from './types';

2022-12-20 11:52 UTC, hustcc commented on __tests__/index.spec.ts
> +test('Node related methods', () => {
看起来是分成了多个片段，可以直接分成多个文件写单测吧，有主题清晰点。后面追加单测也知道往哪里加。

2022-12-20 11:52 UTC, hustcc commented on src/Graph.ts
> +    // FIXME: Should deep clone nodes, edges, and tree structures.
nit: 如果有 node edge Class 的话，递归 clone，就简洁。很多~

2023-01-09 08:14 UTC, YiSiWang commented on src/index.ts
> +export * from './types';
TS 不支持 export type * from 的
https://stackoverflow.com/questions/63588268/export-all-types-and-just-types-from-typescript-module

2023-01-10 03:34 UTC, merged